import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { createId } from '@paralleldrive/cuid2';
import { tenantsTable } from './tenants';
import { studentsTable } from './students';
import { academicYearsTable } from './academic_years';
import { reportTemplatesTable } from './report_templates';
import { usersTable } from './users';

export const generatedReportsTable = sqliteTable('generated_reports', {
  // Primary Key
  reportId: text('report_id')
    .primaryKey()
    .$defaultFn(() => createId()),
  
  // Foreign Keys
  tenantId: text('tenant_id')
    .references(() => tenantsTable.tenantId)
    .notNull(),
  
  studentId: text('student_id')
    .references(() => studentsTable.studentId)
    .notNull(),
  
  academicYearId: text('academic_year_id')
    .references(() => academicYearsTable.academicYearId)
    .notNull(),
  
  templateId: text('template_id')
    .references(() => reportTemplatesTable.templateId)
    .notNull(),
  
  // Semester
  semester: text('semester', { enum: ['1', '2'] }).notNull(),
  
  // File URL (PDF di storage)
  pdfUrl: text('pdf_url'),
  
  // Status Generate
  status: text('status', { 
    enum: ['pending', 'processing', 'completed', 'failed'] 
  }).default('pending'),
  
  // Token Cost
  tokenUsed: integer('token_used').default(0),
  
  // Generated By
  generatedBy: text('generated_by')
    .references(() => usersTable.userId)
    .notNull(),
  
  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp' })
    .$defaultFn(() => new Date()),
  completedAt: integer('completed_at', { mode: 'timestamp' }),
});
