import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { createId } from '@paralleldrive/cuid2';
import { tenantsTable } from './tenants';
import { teachersTable } from './teachers';
import { classesTable } from './classes';
import { subjectsTable } from './subjects';
import { attendanceTable } from './attendance';

export const teachingJournalTable = sqliteTable('teaching_journal', {
  // Primary Key
  journalId: text('journal_id')
    .primaryKey()
    .$defaultFn(() => createId()),
  
  // Foreign Keys
  tenantId: text('tenant_id')
    .references(() => tenantsTable.tenantId)
    .notNull(),
  
  teacherId: text('teacher_id')
    .references(() => teachersTable.teacherId)
    .notNull(),
  
  classId: text('class_id')
    .references(() => classesTable.classId)
    .notNull(),
  
  subjectId: text('subject_id')
    .references(() => subjectsTable.subjectId)
    .notNull(),
  
  // Link ke Attendance (trigger)
  attendanceId: text('attendance_id')
    .references(() => attendanceTable.attendanceId),
  
  // Tanggal Mengajar
  date: integer('date', { mode: 'timestamp' }).notNull(),
  
  // Materi
  material: text('material'),
  
  // Metode Pembelajaran
  method: text('method', { 
    enum: ['tatap_muka', 'daring', 'hybrid'] 
  }).default('tatap_muka'),
  
  // Learning Outcome
  learningOutcome: text('learning_outcome'),
  
  // Catatan Guru
  notes: text('notes'),
  
  // Auto-generated dari attendance?
  autoGenerated: integer('auto_generated', { mode: 'boolean' }).default(false),
  
  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp' })
    .$defaultFn(() => new Date()),
});
